name: Release CVs

on:
  push:
    tags:
      - "*" # Any tag
      
permissions:
  contents: write
  
jobs:
  call_rendercv_workflow:
    name: Render CVs
    uses: ./.github/workflows/rendercv.yaml

  build:
    needs: call_rendercv_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Download RenderCV Output
        uses: actions/download-artifact@v4
        with:
          name: RenderCV Output
          path: rendercv_output
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            rendercv_output/*_CV_*.pdf
            rendercv_output/*_CV_*.tex
          generate_release_notes: true
          make_latest: true
