name: Release CVs

on:
  push:
    tags:
      - "*" # Any tag

permissions:
  contents: write

jobs:
  call_render_workflow:
    name: Render CVs
    uses: ./.github/workflows/render.yaml

  build:
    needs: call_render_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Download CV Output
        uses: actions/download-artifact@v4
        with:
          name: CV Output
          path: cv_output
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cv_output/*_CV_*.pdf
            cv_output/*_CV_*.tex
          generate_release_notes: true
          make_latest: true
