name: Render CVs

on:
  push:
    branches:
      - main
  workflow_call: # to make the workflow triggerable from other workflows (release.yaml)

permissions:
  contents: write

jobs:
  rendercv:
    name: Render CVs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install RenderCV
        run: |
          pip install -r requirements.txt
      - name: RenderCV en
        run: |
          cd src
          cv_file=$(find .  -maxdepth 1 -type f -name "*_CV_en.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No RenderCV file found!"
            exit 1
          fi
          cd ..
          rendercv render src/$cv_file --pdf-path ${cv_file%.yaml}.pdf --latex-path ${cv_file%.yaml}.tex
      - name: RenderCV it
        run: |
          cd src
          cv_file=$(find .  -maxdepth 1 -type f -name "*_CV_it.yaml" | head -n 1)
          if [ -z "$cv_file" ]; then
            echo "No RenderCV file found!"
            exit 1
          fi
          cd ..
          rendercv render src/$cv_file --pdf-path ${cv_file%.yaml}.pdf --latex-path ${cv_file%.yaml}.tex
      - name: Upload as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: ./*_CV_*
