name: Render CVs

on:
  push:
    branches:
      - main
  workflow_dispatch: # to allow manual runs from the Actions tab
  workflow_call: # to make the workflow triggerable from other workflows (release.yaml)

permissions:
  contents: read

jobs:
  rendercv:
    name: Render CVs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install RenderCV
        run: pip install -r requirements.txt
      - name: Render CVs
        run: |
          shopt -s nullglob
          cv_files=(src/*_CV_*.yaml)
          if [ ${#cv_files[@]} -eq 0 ]; then
            echo "No RenderCV files found!"
            exit 1
          fi
          for cv_file in "${cv_files[@]}"; do
            base=$(basename "$cv_file" .yaml)
            rendercv render "$cv_file" --pdf-path "$base.pdf" --latex-path "$base.tex"
          done
      - name: Upload as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: RenderCV Output
          path: |
            ./*_CV_*.pdf
            ./*_CV_*.tex
