name: Render CVs

on:
  push:
    branches:
      - main
  workflow_dispatch: # to allow manual runs from the Actions tab
  workflow_call: # to make the workflow triggerable from other workflows (release.yaml)

permissions:
  contents: read

jobs:
  render:
    name: Render CVs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-basic
            amsmath
            bookmark
            changepage
            charter
            enumitem
            eso-pic
            etoolbox
            fontawesome5
            geometry
            hyperref
            hyphenat
            iftex
            lastpage
            lm
            needspace
            paracol
            psnfss
            titlesec
            tools
            xcolor
      - name: Render CVs
        run: |
          shopt -s nullglob
          cv_files=(src/*_CV_*.yaml)
          if [ ${#cv_files[@]} -eq 0 ]; then
            echo "No CV files found!"
            exit 1
          fi
          for cv_file in "${cv_files[@]}"; do
            base=$(basename "$cv_file" .yaml)
            python render.py "$cv_file" --latex-path "$base.tex" --pdf-path "$base.pdf"
          done
      - name: Upload as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV Output
          path: |
            ./*_CV_*.pdf
            ./*_CV_*.tex
